import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import NextTopLoader from "nextjs-toploader";
import { ThemeProvider } from "@/providers/ThemeProvider";
import TopBar from "@/components/TopBar/TopBar";
import { ScrollArea } from "@/components/ui/ScrollArea";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// eslint-disable-next-line react-refresh/only-export-components
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <ScrollArea className="h-dvh">
            <NextTopLoader showSpinner={false} color="hsl(var(--primary))" />
            <TopBar />
            <div className="flex w-full items-center justify-center">
              <div className="w-full max-w-screen-3xl p-2">{children}</div>
            </div>
          </ScrollArea>
        </ThemeProvider>
      </body>
    </html>
  );
}
